name: Test docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start
      run: |
        export TEST_ENV=$RANDOM$RANDOM >> $GITHUB_ENV
        echo $TEST_ENV
    - name: Clean
      if: always()
      run: echo ${{ env.TEST_ENV }}
