name: Test docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start
      env:
        TEST_ENV: ${{ $RANDOM$RANDOM }}
      run: echo $TEST_ENV
