name: Test docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start
      env:
        FOO: ${{ github.actor }}-${{ github.run_id }}-${{ github.run_attempt }}
      run: echo ${{ env.FOO }}
    - name: Clean
      if: always()
      run: echo ${{ env.FOO }}
